DELETE http://localhost:3001/api/persons/958


###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Tye Rooth",
    "number": "123456789"
}


###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "This Guy"
}